export const eventList = [
  {
    id: 1,
    sectionTitle: 'Events',
    title: 'Geschichten für eine (R)Evolution',
    image: '/images/geschichten-fuer-eine-revolution.jpeg',
    alt: 'program1',
    copyright: '© Andres Beltran',
    date: '12.12.12',
    location: 'K19',
    city: 'Berlin',
    address: 'Kreutziger Str.19',
    postal: '99999',
    description:
      'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.',
    eventLink: 'www.facebook.com',
  },
  {
    id: 2,
    title: 'title 2',
    image: '/images/program2.jpeg',
    alt: 'program2',
    copyright: '© Johanna Wollin',
    date: '12.12.12',
    location: 'K19',
    city: 'Berlin',
    address: 'Kreutziger Str.19',
    postal: '99999',
    description:
      'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.',
    eventLink: 'www.facebook.com',
  },
  {
    id: 3,
    title: 'title 3',
    image: '/images/program3.jpeg',
    alt: 'program3',
    copyright: '© Johanna Wollin',
    date: '12.12.12',
    location: 'K19',
    city: 'Berlin',
    address: 'Kreutziger Str.19',
    postal: '99999',
    description:
      'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.',
  },
  {
    id: 4,
    image: '/images/program4.png',
    alt: 'program4',
    copyright: '© Andres Beltran',
    date: '12.12.12',
    location: 'K19',
    city: 'Berlin',
    address: 'Kreutziger Str.19',
    postal: '99999',
    title: 'title 4',
    description:
      'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.',
  },
  {
    id: 5,
    title: 'title 5',
    image: '/images/program2.jpeg',
    alt: 'program2',
    copyright: '© Johanna Wollin',
    date: '12.12.12',
    location: 'K19',
    city: 'Berlin',
    address: 'Kreutziger Str.19',
    postal: '99999',
    description:
      'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.',
  },
  {
    id: 6,
    title: 'title 6',
    image: '/images/program3.jpeg',
    alt: 'program3',
    copyright: '© Johanna Wollin',
    date: '12.12.12',
    location: 'K19',
    city: 'Berlin',
    address: 'Kreutziger Str.19',
    postal: '99999',
    description:
      'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.',
  },
];
